// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFCjwUaQ-zhDyPhmr7AqU-xkeMKoO9ICw',
    appId: '1:961463394438:web:fc6add03adb96129fb3107',
    messagingSenderId: '961463394438',
    projectId: 'sc-project-b3a67',
    authDomain: 'sc-project-b3a67.firebaseapp.com',
    storageBucket: 'sc-project-b3a67.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC78bkY5NA4xDiwgB_eJIC3TAY-Fn6HaGg',
    appId: '1:961463394438:android:5c785c3bb9b47cd6fb3107',
    messagingSenderId: '961463394438',
    projectId: 'sc-project-b3a67',
    storageBucket: 'sc-project-b3a67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJQApPW3bg93tYv7FB7rQdA68t940_N9E',
    appId: '1:961463394438:ios:f11dda521f6da877fb3107',
    messagingSenderId: '961463394438',
    projectId: 'sc-project-b3a67',
    storageBucket: 'sc-project-b3a67.firebasestorage.app',
    iosBundleId: 'com.example.busManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJQApPW3bg93tYv7FB7rQdA68t940_N9E',
    appId: '1:961463394438:ios:f11dda521f6da877fb3107',
    messagingSenderId: '961463394438',
    projectId: 'sc-project-b3a67',
    storageBucket: 'sc-project-b3a67.firebasestorage.app',
    iosBundleId: 'com.example.busManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFCjwUaQ-zhDyPhmr7AqU-xkeMKoO9ICw',
    appId: '1:961463394438:web:15dd2336e1526facfb3107',
    messagingSenderId: '961463394438',
    projectId: 'sc-project-b3a67',
    authDomain: 'sc-project-b3a67.firebaseapp.com',
    storageBucket: 'sc-project-b3a67.firebasestorage.app',
  );
}
